[package]
name = "mailcrush"
version = "0.1.0"
authors = ["Olivier ROLAND <newca12@users.noreply.github.com>"]
description = "A high-efficiency mail lossless compression tool that deconstructs emails for maximum compression"
homepage = "https://github.com/newca12/mailcrush"
repository = "https://github.com/newca12/mailcrush.git"
keywords = ["email", "mail", "compression", "tool", "cli"]
categories = ["email", "compression", "command-line-utilities"]
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
base64 = "0.22"
chrono = "0.4.43"
clap = { version = "4.5.56", features = ["derive"] }
flate2 = "1.1"
lz4_flex = "0.12.0"
mail-parser = { version = "0.11.1", features = ["full_encoding", "serde"] } 
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
zstd = "0.13"